image: ghcr.io/cpp-review-dune/introductory-review/jupyter-dolfinx

tasks:
  - name: Starting server
    command: |
      Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      startJupyter &

ports:
  - port: 8888
    onOpen: open-browser
